# Generated by Django 2.2.4 on 2021-04-19 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_liked_song_playlist_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songId',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='songId',
            field=models.CharField(default=True, max_length=200),
        ),
        migrations.DeleteModel(
            name='Liked_Song',
        ),
    ]
