# Generated by Django 2.2.4 on 2021-04-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0005_liked_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='liked_song',
            name='songId',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
